name: R Analysis

on:
  push:
    paths:
      - "analysis/**"
      - "data/**"
  pull_request:
    paths:
      - "analysis/**"
      - "data/**"

jobs:
  correlation:
    if: contains(github.event.head_commit.message, 'correlation') || contains(join(github.event.commits.*.modified, ','), 'analysis/correlation_analysis.R') || contains(join(github.event.commits.*.modified, ','), 'data/R_factor_data.csv')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
      - run: Rscript analysis/correlation_analysis.R

  factor:
    if: contains(github.event.head_commit.message, 'factor') || contains(join(github.event.commits.*.modified, ','), 'analysis/factor_analysis.R') || contains(join(github.event.commits.*.modified, ','), 'data/R_factor_data.csv')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
      - run: Rscript analysis/factor_analysis.R

  survival:
    if: contains(github.event.head_commit.message, 'survival') || contains(join(github.event.commits.*.modified, ','), 'analysis/survival_analysis.R') || contains(join(github.event.commits.*.modified, ','), 'data/R_survival_data.csv')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
      - run: Rscript analysis/survival_analysis.R
